# Generated by Django 5.2.7 on 2025-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
