# Generated by Django 5.2.7 on 2025-11-22 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0003_alter_paste_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="admin_removal_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paste",
            name="admin_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paste",
            name="admin_removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_pastes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paste",
            name="is_removed_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
